export let quoteList = [
    'Do You Even Pizza Night?',
    'First Slice!',
    "Rookie Numbers.",
    "Heard That Last One Was Good.", 
    "What's Next?",
    'Nice Choice!',
    'Still Hungry?',
    'Cha Cha Cha Chillin!',
    'What Movie Has The Best Soundtrack?',
    "You're Earning That XP!",
    'Good Times.',
    'Interesting Viewpoint.',
    "We'll Talk Games Next Time.",
    "How You Holding Up?",
    "Couch Locked.",
    "Running Out Of Options.",
    "Stuffed, But So Close...",
    "Dude, How Have We Made It This Far?",
    'Just One Last Piece, Man.',
    "Maxed Out!"
]